### ISSUE TITLE
Do you mind if I write a request to be added to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [jetspiking/AndME#3]

**Comment by jetspiking** [comment]
Hi @Artem13327, not at all, would be cool if it is included there!

**Comment by jetspiking** [comment]
@Artem13327, here is my information:

AuthorName: Dustin Hendriks
AuthorEmail: dustinhendriks2000@gmail.com
AuthorWebSite: https://www.linkedin.com/in/dustinhendriks/
WebSite: https://github.com/jetspiking/AndME
IssueTracker: https://github.com/jetspiking/AndME/issues

(ApplicationName: AndME)

**Comment by jetspiking** [comment]
Ah, is this a requirement? I'd rather not adjust my repository with (for the application irrelevant) data just because F-Droid needs it.

**Comment by IzzySoft** [comment]
There you go :smiley:

**Comment by jetspiking** [comment]
Thanks @Artem13327 for contacting @IzzySoft 👍

**Comment by IzzySoft** [comment]
@jetspiking gladly done! But not being an Android dev myself, I'm afraid this was all I can contribute in terms of PRs (especially givven the many tasks already on my table).

@Artem13327 depends. It's a means of contact. The only other ones are Gmail (I'd never reach out on that, nor on Hotmail & Co, for privacy reasons; if you send a mail from such my server would auto-reply for me suggesting you to use a "decent mail provider") or Github (which some people hesitate using for the very same reason). So a libre social network (like a Fediverse instance) might be welcome, if there are no other means.

Btw: Where did you see it used in AuthorWebSite? All I have set here is:

```yaml
AuthorName: Dustin Hendriks
AuthorEmail: d.hendriks.tweakers@gmail.com
SourceCode: https://github.com/jetspiking/AndME
IssueTracker: https://github.com/jetspiking/AndME/issues
Changelog: https://github.com/jetspiking/AndME/releases
Donate: https://www.buymeacoffee.com/DustinHendriks
```

Ah, above in the comment – and yes, for those I agree (we're speaking F/LOSS here, and all those services are proprietary – would be nice to see at least a single libre one; many f/loss devs are e.g. somewhere on the Fediverse). Also `Website` should not point to the Github account (that can already be deduced from `SourceCode`).

Btw: For donation links you might wish to take a look at Github's `FUNDING.yaml` (to be placed either into `/.github` or right in the repo root). Depending which services you use:

```yaml
# These are supported funding model platforms

github: [ jetspiking ] # Github Sponsors if you have enrolled to that
patreon: # Replace with a single Patreon username
open_collective: # Your OpenCollective handle
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Your Liberapay UserName
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://www.buymeacoffee.com/DustinHendriks'] # up to 4 URLs
```

That would be picked up automatically by F-Droid (and also by my updater), giving you an easy way to update it when needed.
